In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr=np.array([1,2,3,4]) # 1D array
arr

array([1, 2, 3, 4])

In [6]:
arr2=np.array([[1,2,3],[4,5,6]]) # 2D array
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros((3,4))  # zerroes array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,5))  # one array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((4,6),5)  # isse ham koi sa bh array bna sakte he 

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [11]:
np.eye(3)  # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(1,100)  # isse range tak array creae ho jayge

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(1,100,5)  


array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [14]:
np.linspace(1,100,5)  # array ko 5 bhag me divide ker deta he 

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [15]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [16]:
# checking array properties
myArr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myArr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
myArr.shape  # array kitni bai kitni ka he bo btata he 

(4, 3)

In [18]:
myArr.size  # array me kitne element he bo btata he 

12

In [20]:
myArr.ndim # array 1d he ya 2d he bo btata he 

2

In [22]:
myArr.dtype  # ye btata he ki aaray kese data store karta he int floate 

dtype('int64')

In [29]:
# changing data type
myArr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')
# myArr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype=np.float32)

In [30]:
myArr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [38]:
n=myArr.astype('float64')

In [39]:

n.dtype

dtype('float64')

In [40]:
myArr.dtype

dtype('float32')

In [42]:
# reshapping and fletering array
myArr2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])


In [43]:
myArr2.shape

(4, 3)

In [44]:
reshaped=myArr2.reshape((3,4))

In [45]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
myArr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
myArr2.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [48]:
flt=myArr2.flatten()
flt

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
# indexing and slicing in numpy array

arr=np.array([1,2,3,4,5,6,78,90,8,6,12])
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[1:])
print(arr[:])
print(arr[:7])

# important slicing
print(arr[:3]) # isse to first three element aa jayge 
print(arr[::5]) # isse her position element aayga array sse jo ham denge 

3
12
[2 3 4]
[ 2  3  4  5  6 78 90  8  6 12]
[ 1  2  3  4  5  6 78 90  8  6 12]
[ 1  2  3  4  5  6 78]
[1 2 3]
[ 1  6 12]
