In [1]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

int64


In [3]:
arr.astype("float64")

array([1., 2., 3., 4., 5.])

In [10]:
# arr = np.array([1.5, 2.7, 3.9],dtype=np.float32)
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)  # Output: float64
 
arr_int = arr.astype(np.int64)  # Converting float to int
# arr_int = arr.astype("int32")
print(arr_int)    # Output: [1 2 3]
print(arr_int.dtype)  # Output: int32

float64
[1 2 3]
int64


In [11]:
arr_int.nbytes

24

In [14]:
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_large,arr_large.nbytes)
print(arr_small,arr_small.nbytes)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000] 24
[1000000 2000000 3000000] 12
int32


In [15]:
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
 
print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [32]:
# string data type
arr_str = np.array(['apple', 'banana', 'cherry'], dtype='U6')  # Unicode string array
print(arr_str)
print(arr_str.dtype)

['apple' 'banana' 'cherry']
<U6


In [36]:
# complex number

arr_complex = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr_complex)

[1.+2.j 3.+4.j 5.+6.j]
