In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 21)

In [3]:
# Print only even numbers.
even_num=arr % 2 == 0
print(arr[even_num])

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# Print numbers greater than 10.
greater_num=arr > 10
print(arr[greater_num])

[11 12 13 14 15 16 17 18 19 20]


In [6]:
# Find the sum of all even numbers.
even_sum=arr % 2 == 0
print("Sum of even numbers : ",np.sum(arr[even_sum]))

Sum of even numbers :  110


In [7]:
# Find the mean of all odd numbers.
odd_mean=arr % 2 == 1
print("Mean of all odd numbers : ",np.mean(arr[odd_mean]))

Mean of all odd numbers :  10.0


In [9]:
# Convert the array into a 4×5 matrix.
reshaped=np.reshape(arr,(4,5))
print(reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [32]:
# Print the last row.
# print(reshaped[3][:])
print(reshaped[3,:])

# Print the second column.
print(reshaped[:,1])


[16 17 18 19 20]
[-1 -1 -1 17]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 15 16 17 18 19 20]


In [13]:
# Find the maximum value in the matrix.
print(np.max(reshaped))

20


In [15]:
# Find the index of value 15.
index = np.where(arr == 15)

print(index)

print(np.where(arr==15))

(array([14]),)
(array([14]),)


In [27]:
# Reverse the array.
# print(arr[::-1])
print(reshaped[::-1])

[[16 17 18 19 20]
 [-1 -1 -1 -1 15]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [28]:
# Replace all numbers less than 15 with -1
reshaped[reshaped<15]=-1
print(reshaped)

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 15]
 [16 17 18 19 20]]


In [40]:
# Count how many elements are greater than 10.
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
# gre_num=arr[arr>10]
# print(gre_num)

# count=0
# for i in gre_num:
#     if i>10:
#         count+=1
# print(f"{count} numbers are greter than 10.")

count = np.sum(arr > 10)

print(count)

155
