In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1,100,(5,5))
print(arr)

[[ 1 16 99 57 27]
 [ 1 39 92 21 94]
 [80 37 81 94 46]
 [11 98 55 95 65]
 [ 5 40 68 88 56]]


In [15]:
# Find the sum of each row.
# for i in range(len(arr)):
#     print(np.sum(arr[i,:]))
print(np.sum(arr, axis=1))

# Find the sum of each column.
print(np.sum(arr, axis=0))


[200 247 338 324 257]
[ 98 230 395 355 288]


In [17]:

# Find the maximum element of each row.
# Find the minimum element of each column.
print(np.max(arr, axis=1))
print(np.min(arr, axis=1))



[99 94 94 98 88]
[ 1  1 37 11  5]


In [19]:
arr = np.random.randint(1,500,100)