In [1]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr[1]

array([4, 5, 6])

In [6]:
# np.sum(arr,axis=0)
np.sum(arr,axis=1)


array([ 6, 15, 24])

In [10]:
print(arr[0][1])

2


In [12]:
print(arr[0,1])

2


In [13]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [14]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [15]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6
 
print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [28]:
# get all rows of girst column
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
first_row=arr3D[:,:,0]
print(first_row.flatten())

# set the first row of each "sheet" in a 3d aaray
print(arr3D[:,0,:])


[ 1  4  7 10]
[[1 2 3]
 [7 8 9]]


In [33]:
# changing data along axis 
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[:,1]=0
print(arr2d)
arr3D[:,:,2]=10
print(arr3D)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
[[[ 0  0 10]
  [ 4  5 10]]

 [[ 7  8 10]
  [10 11 10]]]
