In [1]:
import numpy as np

In [5]:
arr=np.array([2,4,4,4,5,5,7,9])

In [6]:
print(np.mean(arr))

5.0


In [7]:
print(np.var(arr))


4.0


In [8]:
print(np.std(arr))


2.0


In [9]:
print(np.max(arr))
print(np.min(arr))

9
2


In [10]:
print(np.prod(arr))
print(np.sum(arr))

201600
40


In [11]:
print(np.median(arr))


4.5


In [18]:
print(np.mod(arr,2)) # gives reminder

[0 0 0 0 1 1 1 1]


In [21]:
print(np.percentile(arr,30))  # ye btata he ki kitna hissa 50%,25,50,75 ke niche he ya uske baraber he 


4.0


In [22]:
print(np.argmax(arr))
print(np.argmin(arr))

7
0


In [36]:
print(np.unique(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))


[2 4 5 7 9]
[ 2  6 10 14 19 24 31 40]
[     2      8     32    128    640   3200  22400 201600]


In [37]:
print(np.log(arr)) # calculate on base e natural base bhi kahte he 


[0.69314718 1.38629436 1.38629436 1.38629436 1.60943791 1.60943791
 1.94591015 2.19722458]


In [38]:
print(np.exp(arr))


[7.38905610e+00 5.45981500e+01 5.45981500e+01 5.45981500e+01
 1.48413159e+02 1.48413159e+02 1.09663316e+03 8.10308393e+03]


In [39]:
print(np.add(arr,5))
print(np.multiply(arr,5))
print(np.subtract(arr,5))
print(np.power(arr,2))
print(np.divide(arr,2))
print(np.square(arr))
print(np.sqrt(arr))
print(np.cbrt(arr))
print(np.abs(arr))

[ 7  9  9  9 10 10 12 14]
[10 20 20 20 25 25 35 45]
[-3 -1 -1 -1  0  0  2  4]
[ 4 16 16 16 25 25 49 81]
[1.  2.  2.  2.  2.5 2.5 3.5 4.5]
[ 4 16 16 16 25 25 49 81]
[1.41421356 2.         2.         2.         2.23606798 2.23606798
 2.64575131 3.        ]
[1.25992105 1.58740105 1.58740105 1.58740105 1.70997595 1.70997595
 1.91293118 2.08008382]
[2 4 4 4 5 5 7 9]


In [42]:
print(np.tan(45))

1.6197751905438615
