In [1]:
# create a numpy aaray with values from 10 to 100 and print its shape
import numpy as np

arr = np.arange(10, 101)

print("Array:")
print(arr)

print("Shape:", arr.shape)

Array:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Shape: (91,)


In [2]:
# comare the time taken to multiply the two python list vs two numpy arrays
import numpy as np
import time

size=10
l1=list(range(size))
l2=list(range(size))

start=time.time()

add=[x*y for x,y in zip(l1,l2)]

end=time.time()

print("pyhton list time taken: ",end-start)

a1=np.array(list(range(size)))
a2=np.array(list(range(size)))

start=time.time()

mul=a1*a2

end=time.time()

print("numpy arrays time taken: ",end-start)

pyhton list time taken:  0.0002503395080566406
numpy arrays time taken:  0.00020456314086914062


In [3]:
# find the memory size of a NumPy array with 1 million elements 
import numpy as np

# Create an array with 1 million elements
arr = np.arange(1000000)

# Memory size in bytes
print("Memory Size (Bytes):", arr.nbytes)

# Memory size in KB
print("Memory Size (KB):", arr.nbytes / 1024)

# Memory size in MB
print("Memory Size (MB):", arr.nbytes / (1024 * 1024))

Memory Size (Bytes): 8000000
Memory Size (KB): 7812.5
Memory Size (MB): 7.62939453125


In [4]:
# Create a 3x3 array filled with random numbers and print its shape 

arr = np.random.rand(3, 3)

print("Array:")
print(arr)

print("Shape:", arr.shape)


Array:
[[0.43438608 0.80803317 0.31432983]
 [0.11995225 0.9630341  0.12005891]
 [0.1673709  0.66674137 0.56870515]]
Shape: (3, 3)


In [5]:
# convert an array of float [1.1,2.2,3.3,4.4] int integer

arr = np.array([1.1, 2.2, 3.3, 4.4])

int_arr = arr.astype(int)   # astype(int) converts each element to an integer.

print("Original Array:", arr)
print("Integer Array:", int_arr)


Original Array: [1.1 2.2 3.3 4.4]
Integer Array: [1 2 3 4]


In [6]:
# use fancy indexing to extract even numbers from [1,2,3,4,5,6,7,8,9,10]
arr=np.array([1,2,3,4,5,6,7,8,9,10])
even=arr%2==0
# even = arr[arr % 2 == 0]
print(arr[even])

[ 2  4  6  8 10]


In [8]:
# reshape of 1D array of size 9 into a 3x3 matrix
arr=np.arange(9)
reshaped=arr.reshape((3,3))
print(reshaped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# create a numpy aaray with values from 10 to 100 and print its shape
import numpy as np

arr = np.arange(10, 101)

print("Array:")
print(arr)

print("Shape:", arr.shape)