In [15]:
# pyhton zip explaination
l1=[1,2,3]
l2=[4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [17]:
# using python list
import numpy as np
import time

size=1_000_000
l1=list(range(size))
l2=list(range(size))
# l1=[1,2,3]
# l2=[4,5,6]
start=time.time()

add=[x+y for x,y in zip(l1,l2)]

end=time.time()
print(add[0:10])


print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.20391631126403809


In [19]:
# using NumPy Arrays
import numpy as np
import time

size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))

start=time.time()

add=l1+l2

end=time.time()
print(add[0:10])

print(end-start)

[ 0  2  4  6  8 10 12 14 16 18]
0.021090269088745117


In [26]:
# creating  1D numpy array
arr1=np.array([1,2,3,4,5,6])
print(arr1)

# creating  2D numpy array
arr2=np.array([[1,2,3],[4,5,6]])
arr2

type(arr1)
arr2.shape

[1 2 3 4 5 6]


(2, 3)

In [30]:
# memory efficiency
import sys
import numpy as np
list_data=list(range(1000))
numpy_data=np.array(list_data)
print(f"Python List Size : {sys.getsizeof(list_data)*len(list_data)} bytes")
# print(f"NumPy Array Size : {numpy_data.nbytes} bytes")
print("numpy array siize : ",numpy_data.nbytes,"bytes")

Python List Size : 8056000 bytes
numpy array siize :  8000 bytes


In [35]:
# vecterization No More Loops

# python list(loop-based)
import time
list1=list(range(10))
start=time.time()
list_sqr=[x**2 for x in list1]
end=time.time()
print(end-start)
print(list_sqr)

# numpy(vexterized)
import numpy as np
arr1=np.array(list1)

start=time.time()
numpy_sqr=arr1 ** 2
end=time.time()
print(end-start)
print(numpy_sqr)



0.0007302761077880859
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.0003108978271484375
[ 0  1  4  9 16 25 36 49 64 81]


In [36]:
# create a numpy aaray with values from 10 to 100 and print its shape
import numpy as np

arr = np.arange(10, 101)

print("Array:")
print(arr)

print("Shape:", arr.shape)

Array:
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
Shape: (91,)


In [40]:
# comare the time taken to multiply the two python list vs two numpy arrays
import numpy as np
import time

size=10
l1=list(range(size))
l2=list(range(size))

start=time.time()

add=[x*y for x,y in zip(l1,l2)]

end=time.time()

print("pyhton list time taken: ",end-start)

a1=np.array(list(range(size)))
a2=np.array(list(range(size)))

start=time.time()

mul=a1*a2

end=time.time()

print("numpy arrays time taken: ",end-start)

pyhton list time taken:  0.0002894401550292969
9
numpy arrays time taken:  0.0002148151397705078


In [41]:
# find the memory size of a NumPy array with 1 million elements 
import numpy as np

# Create an array with 1 million elements
arr = np.arange(1000000)

# Memory size in bytes
print("Memory Size (Bytes):", arr.nbytes)

# Memory size in KB
print("Memory Size (KB):", arr.nbytes / 1024)

# Memory size in MB
print("Memory Size (MB):", arr.nbytes / (1024 * 1024))

Memory Size (Bytes): 8000000
Memory Size (KB): 7812.5
Memory Size (MB): 7.62939453125
